using Content.Shared.CCVar;
using Content.Shared.DeltaV.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.DeltaV.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        EnableDiscordOocNameColor.OnToggled += OnCheckBoxToggled;
        EnableDiscordOocTextColor.OnToggled += OnCheckBoxToggled;

        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(DCCVars.NoVisionFilters);
        EnableDiscordOocNameColor.Pressed = _cfg.GetCVar(CCVars.ShowOocDiscordNameColor);
        EnableDiscordOocTextColor.Pressed = _cfg.GetCVar(CCVars.ShowOocDiscordTextColor);

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(DCCVars.NoVisionFilters, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(CCVars.ShowOocDiscordNameColor, EnableDiscordOocNameColor.Pressed);
        _cfg.SetCVar(CCVars.ShowOocDiscordTextColor, EnableDiscordOocTextColor.Pressed);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isNoVisionFiltersSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(DCCVars.NoVisionFilters);
        var isDiscordOocNameColorSame = EnableDiscordOocNameColor.Pressed == _cfg.GetCVar(CCVars.ShowOocDiscordNameColor);
        var isDiscordOocTextColorSame = EnableDiscordOocTextColor.Pressed == _cfg.GetCVar(CCVars.ShowOocDiscordTextColor);

        ApplyButton.Disabled = isNoVisionFiltersSame && isDiscordOocNameColorSame && isDiscordOocTextColorSame;
    }
}
